openapi: 3.2.0
info:
  title: PSA Ledgers API
  version: v1
servers:
- url: https://dev-cloud.acronis.com/api/advanced-automation/v1
  variables: {}
tags:
- name: Ledgers
paths:
  /Ledgers:
    get:
      operationId: FetchLedgers
      description: Fetches a list of all ledgers.
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLedgersSearchResponse'
      security:
      - oauth2: []
      tags:
      - Ledgers
      summary: Fetch ledgers
      x-summary-source: derived
      x-operation-id-source: normalized
      x-operation-id-original: Fetch ledgers
components:
  schemas:
    LedgerPartial:
      type: object
      additionalProperties: false
      required:
      - Active
      - CreationDate
      - Description
      - ExternalId
      - Id
      - Number
      properties:
        Active:
          description: ''
          type: boolean
        CreationDate:
          description: ''
          type: string
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?$
        Description:
          type:
          - string
          - 'null'
        ExternalId:
          type:
          - string
          - 'null'
        Id:
          description: ''
          example: 00000000-0000-0000-0000-000000000000
          type: string
          pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
        Number:
          description: ''
          type: string
    GetLedgersSearchResponse:
      example:
        Ledgers:
        - Id: 00000000-0000-0000-0000-000000000000
          Number: ''
          Description: ''
          Active: true
          CreationDate: '0001-01-01T00:00:00Z'
          ExternalId: ''
        - Id: 00000000-0000-0000-0000-000000000000
          Number: ''
          Description: ''
          Active: true
          CreationDate: '0001-01-01T00:00:00Z'
          ExternalId: ''
        Paging:
          AmountTotalItems: 0
          AmountRecordsFound: 0
          AmountOfPages: 0
      type: object
      additionalProperties: false
      required:
      - Ledgers
      - Paging
      properties:
        Ledgers:
          type: array
          items:
            $ref: '#/components/schemas/LedgerPartial'
        Paging:
          $ref: '#/components/schemas/Paging'
    Paging:
      type: object
      additionalProperties: false
      required:
      - AmountTotalItems
      - AmountRecordsFound
      - AmountOfPages
      properties:
        AmountTotalItems:
          type: integer
        AmountRecordsFound:
          type: integer
        AmountOfPages:
          type: integer
  securitySchemes:
    oauth2:
      type: oauth2
      description: A description of the security scheme.
      flows:
        clientCredentials:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        password:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        authorizationCode:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          authorizationUrl: https://dev-cloud.acronis.com/api/2/idp/authorize
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
x-roles:
- name: public
  id: '1'
  description: public role
  x-tags:
  - public
- name: private
  id: '2'
  description: private role
  x-tags:
  - private
