openapi: 3.2.0
info:
  title: PSA Uploaded Files API
  version: v1
servers:
- url: https://dev-cloud.acronis.com/api/advanced-automation/v1
  variables: {}
tags:
- name: UploadedFiles
paths:
  /UploadedFiles:
    get:
      operationId: Fetch helpdesk attachment
      description: Lists attachments available for a ticket
      parameters:
      - name: customer
        in: query
        schema:
          type: string
      - name: referenceNumber
        in: query
        schema:
          type: string
      - name: ticketId
        required: true
        in: query
        schema:
          $ref: '#/components/schemas/Guid'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                - FileName
                - FileSizeInBytes
                - FileSrc
                - FileType
                properties:
                  FileName:
                    type: string
                  FileSizeInBytes:
                    type: integer
                  FileSrc:
                    type: string
                  FileType:
                    type: string
      security:
      - oauth2: []
      tags:
      - UploadedFiles
      summary: Fetch helpdesk attachment
      x-summary-source: derived
components:
  schemas:
    Guid:
      example: 00000000-0000-0000-0000-000000000000
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
  securitySchemes:
    oauth2:
      type: oauth2
      description: A description of the security scheme.
      flows:
        clientCredentials:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        password:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        authorizationCode:
          scopes:
            urn:acronis.com::advanced_automation::advanced_automation_client: ''
            urn:acronis.com::advanced_automation::advanced_automation_client_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_admin: ''
            urn:acronis.com::advanced_automation::advanced_automation_director: ''
            urn:acronis.com::advanced_automation::advanced_automation_engineer: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance: ''
            urn:acronis.com::advanced_automation::advanced_automation_finance_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_group_manager: ''
            urn:acronis.com::advanced_automation::advanced_automation_hr: ''
            urn:acronis.com::advanced_automation::advanced_automation_sales: ''
          authorizationUrl: https://dev-cloud.acronis.com/api/2/idp/authorize
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
x-roles:
- name: public
  id: '1'
  description: public role
  x-tags:
  - public
- name: private
  id: '2'
  description: private role
  x-tags:
  - private
