openapi: 3.2.0
info:
  title: Vault Manager Healthcheck API
  version: v1
servers:
- url: https://dev-cloud.acronis.com/api/vault_manager/v1
  variables: {}
tags:
- name: Health Check
paths:
  /healthcheck:
    get:
      operationId: HealthCheck
      description: Health check route. Returns basic information about service.
      responses:
        '200':
          description: ''
      security:
      - oauth2: []
      tags:
      - Health Check
      summary: Health check
      x-summary-source: derived
      x-operation-id-source: normalized
      x-operation-id-original: Health check
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          scopes:
            vault_manager::system_admin: ''
            vault_manager::admin: ''
            vault_manager::core_restore: ''
            vault_manager::c2c_restore: ''
            vault_manager::orphanage_readwrite: ''
            vault_manager::read: ''
            protection::readonly: ''
            root_admin: ''
            partner_admin: ''
            infra_admin: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        authorizationCode:
          scopes:
            vault_manager::system_admin: ''
            vault_manager::admin: ''
            vault_manager::core_restore: ''
            vault_manager::c2c_restore: ''
            vault_manager::orphanage_readwrite: ''
            vault_manager::read: ''
            protection::readonly: ''
            root_admin: ''
            partner_admin: ''
            infra_admin: ''
          authorizationUrl: https://dev-cloud.acronis.com/api/2/idp/authorize
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
x-roles:
- name: public
  id: '1'
  description: public role
  x-tags:
  - public
- name: private
  id: '2'
  description: private role
  x-tags:
  - private
