openapi: 3.2.0
info:
  title: Account Management Registration Tokens API
  version: '2'
servers:
- url: https://dev-cloud.acronis.com/api/2
  variables: {}
tags:
- name: Registration Tokens
paths:
  /registration_tokens:
    get:
      operationId: FetchRegistrationTokens_0
      description: '*DEPRECATED.* Use `/api/2/tenants/{tenant_id}/registration_tokens`.


        Fetches a list of registration tokens.'
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrationTokensList'
        '401':
          description: Method required an authenticated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '403':
          description: Current user is not authorized to access this endpoint or its method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '415':
          description: Requested type in the `Accept` request header is not supported.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
      security:
      - basicAuth: []
      - oauth2:
        - urn:acronis.com::account-server::oauth2_client_admin
      tags:
      - Registration Tokens
      summary: Fetch registration tokens 0
      x-summary-source: derived
    post:
      operationId: CreateRegistrationToken_0
      description: '*DEPRECATED.* Use /api/2/tenants//registration_tokens.


        Creates a registration token.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registrationTokenPost'
      responses:
        '201':
          description: Registration token was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrationToken'
        '401':
          description: Method required an authenticated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '403':
          description: Current user is not authorized to access this endpoint or its method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '415':
          description: Requested type in the `Accept` request header is not supported.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
      security:
      - basicAuth: []
      - oauth2:
        - urn:acronis.com::account-server::oauth2_client_admin
      tags:
      - Registration Tokens
      summary: Create registration token 0
      x-summary-source: derived
  /registration_tokens/{token_id}:
    delete:
      operationId: DeleteRegistrationToken
      description: Deletes a registration token by ID.
      parameters:
      - name: token_id
        description: Registration Token ID (UUID).
        required: true
        in: path
        schema:
          description: Registration Token ID (UUID).
          type: string
          pattern: '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}'
          minLength: 36
          maxLength: 36
      responses:
        '204':
          description: Registration token was removed.
          content: {}
        '401':
          description: Method required an authenticated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '403':
          description: Current user is not authorized to access this endpoint or its method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
        '415':
          description: Requested type in the `Accept` request header is not supported.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorScheme'
      security:
      - basicAuth: []
      - oauth2:
        - urn:acronis.com::account-server::oauth2_client_admin
      tags:
      - Registration Tokens
      summary: Delete registration token
      x-summary-source: derived
components:
  schemas:
    item1:
      description: RFC3339 Formatted date.
      type: string
      pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?([\+\-]\d{2}\:\d{2})?
      minLength: 19
      maxLength: 32
    registrationTokensList:
      example:
        items:
        - id: 2
          token: 27F9-5234-41C3
          tenant_id: '11'
          tenant_uuid: 4b07e4a1-a49b-4d4e-b8f2-253f1fef98ad
          created_at: '2022-04-02T18:46:45Z'
          expires_at: '2022-04-05T18:46:45Z'
          scopes:
          - urn:acronis.com:tenant-id:734fe814-748a-41cb-8a94-60e18fb3c442:backup_agent_admin
          - urn:acronis.com::policy_management:4b07e4a1-a49b-4d4e-b8f2-253f1fef98ad|10858a46-db9b-4725-aa60-fff6252841fd:apply_revoke
        - id: 3
          token: F8CA-2DD1-41F1
          tenant_id: '1363521'
          tenant_uuid: 00bc0d4a-9879-40bf-823a-77c01b197dc1
          created_at: '2022-04-02T18:57:46Z'
          expires_at: '2022-04-05T18:57:46Z'
          scopes:
          - urn:acronis.com:tenant-id:1e3d306e-85ad-454c-b4f6-2bd73c83b9a1:backup_agent_admin
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/registrationToken'
    uuid:
      type: string
      pattern: '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}'
      minLength: 36
      maxLength: 36
    registrationToken:
      example:
        id: 2
        token: 27F9-5234-41C3
        tenant_id: '11'
        tenant_uuid: 4b07e4a1-a49b-4d4e-b8f2-253f1fef98ad
        created_at: '2022-04-02T18:46:45Z'
        expires_at: '2022-04-05T18:46:45Z'
        scopes:
        - urn:acronis.com:tenant-id:734fe814-748a-41cb-8a94-60e18fb3c442:backup_agent_admin
        - urn:acronis.com::policy_management:4b07e4a1-a49b-4d4e-b8f2-253f1fef98ad|10858a46-db9b-4725-aa60-fff6252841fd:apply_revoke
      type: object
      additionalProperties: false
      required:
      - id
      - token
      - created_at
      - expires_at
      - tenant_id
      - scopes
      properties:
        id:
          description: Initial registration token unique identifier.
          type: integer
        token:
          description: Initial registration token.
          type: string
          pattern: '[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}'
        created_at:
          $ref: '#/components/schemas/item1'
        expires_at:
          $ref: '#/components/schemas/item1'
        tenant_id:
          description: Numeric identifier of the resource owner tenant.
          type: string
          pattern: \d+
        tenant_uuid:
          $ref: '#/components/schemas/uuid'
        scopes:
          description: 'Access scopes that are applied to the registered resource. The following access scope patterns are available:

            - `urn:acronis.com:tenant-id:{personal_tenant_id}:backup_agent_admin` - binds the resource to the user by personal tenant ID specified in `{personal_tenant_id}`.

            - `urn:acronis.com::policy_management:{tenant_id}|{policy_id}:apply_revoke` - applies a protection plan to a resource by policy ID specified in `{policy_id}` from a resource owner tenant specified in `{tenant_id}`.'
          type: array
          items:
            type: string
    registrationTokenPost:
      example:
        tenant_id: 72acaf6a-b15a-11e6-80f5-76304dec7eb7
        expires_in: 3600
        scopes:
        - urn:acronis.com:tenant-id:734fe814-748a-41cb-8a94-60e18fb3c442:backup_agent_admin
      type: object
      additionalProperties: false
      required:
      - expires_in
      - scopes
      properties:
        tenant_id:
          $ref: '#/components/schemas/uuid'
        expires_in:
          description: Token expiration time in seconds. Should be less than or equal to one year.
          type: integer
        scopes:
          description: 'Access scopes that are applied to the registered resource. The following access scope patterns are available:

            - `urn:acronis.com:tenant-id:{personal_tenant_id}:backup_agent_admin` - binds the resource to the user by personal tenant ID specified in `{personal_tenant_id}`.

            - `urn:acronis.com::policy_management:{tenant_id}|{policy_id}:apply_revoke` - applies a protection plan to a resource by policy ID specified in `{policy_id}` from a resource owner tenant specified in `{tenant_id}`.'
          type: array
          items:
            type: string
    errorScheme:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - code
          - domain
          - message
          - details
          properties:
            code:
              oneOf:
              - type: string
              - type: integer
            context:
              type: object
            domain:
              description: This field can have a null value.
              type:
              - string
              - 'null'
            message:
              type: string
            details:
              description: Additional info.
              type: object
              properties:
                info:
                  description: This field can have a null value.
                  type:
                  - string
                  - 'null'
            data:
              type: array
              items:
                type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          scopes:
            urn:acronis.com::account-server::root_admin: ''
            urn:acronis.com::account-server::partner_admin: ''
            urn:acronis.com::account-server::company_admin: ''
            urn:acronis.com::account-server::unit_admin: ''
            urn:acronis.com::account-server::readonly_admin: ''
            urn:acronis.com::account-server::tenant_admin: ''
            urn:acronis.com::account-server::tenant_viewer: ''
            urn:acronis.com::account-server::user_admin: ''
            urn:acronis.com::account-server::replication_manager: ''
            urn:acronis.com::account-server::managed_clients_admin: ''
            urn:acronis.com::account-server::oauth2_client_admin: ''
            urn:acronis.com::account-server::legal_docs_signer: ''
            urn:acronis.com::accounts::email_token_requester: ''
            urn:acronis.com::accounts::licensing_admin: ''
            urn:acronis.com::accounts::usage_reporter: ''
            urn:acronis.com::backup::backup_user: ''
            urn:acronis.com::backup::protection_admin: ''
            urn:acronis.com::files_cloud::sync_share_user: ''
            urn:acronis.com::acep::consumer: ''
            urn:acronis.com::account-server::security_groups_admin: ''
            urn:acronis.com::account-server::security_groups_viewer: ''
            urn:acronis.com::account-server::token_introspector: ''
            urn:acronis.com::account-server::custom_role_manager: ''
            urn:acronis.com::account-server::custom_role_viewer: ''
          tokenUrl: /api/2/idp/token
        authorizationCode:
          scopes:
            urn:acronis.com::account-server::root_admin: ''
            urn:acronis.com::account-server::partner_admin: ''
            urn:acronis.com::account-server::company_admin: ''
            urn:acronis.com::account-server::unit_admin: ''
            urn:acronis.com::account-server::readonly_admin: ''
            urn:acronis.com::account-server::tenant_admin: ''
            urn:acronis.com::account-server::tenant_viewer: ''
            urn:acronis.com::account-server::user_admin: ''
            urn:acronis.com::account-server::replication_manager: ''
            urn:acronis.com::account-server::managed_clients_admin: ''
            urn:acronis.com::account-server::oauth2_client_admin: ''
            urn:acronis.com::account-server::legal_docs_signer: ''
            urn:acronis.com::accounts::email_token_requester: ''
            urn:acronis.com::accounts::licensing_admin: ''
            urn:acronis.com::accounts::usage_reporter: ''
            urn:acronis.com::backup::backup_user: ''
            urn:acronis.com::backup::protection_admin: ''
            urn:acronis.com::files_cloud::sync_share_user: ''
            urn:acronis.com::acep::consumer: ''
            urn:acronis.com::account-server::security_groups_admin: ''
            urn:acronis.com::account-server::security_groups_viewer: ''
            urn:acronis.com::account-server::token_introspector: ''
            urn:acronis.com::account-server::custom_role_manager: ''
            urn:acronis.com::account-server::custom_role_viewer: ''
          authorizationUrl: /api/2/idp/authorize
          tokenUrl: /api/2/idp/token
        password:
          scopes:
            urn:acronis.com::account-server::root_admin: ''
            urn:acronis.com::account-server::partner_admin: ''
            urn:acronis.com::account-server::company_admin: ''
            urn:acronis.com::account-server::unit_admin: ''
            urn:acronis.com::account-server::readonly_admin: ''
            urn:acronis.com::account-server::tenant_admin: ''
            urn:acronis.com::account-server::tenant_viewer: ''
            urn:acronis.com::account-server::user_admin: ''
            urn:acronis.com::account-server::replication_manager: ''
            urn:acronis.com::account-server::managed_clients_admin: ''
            urn:acronis.com::account-server::oauth2_client_admin: ''
            urn:acronis.com::account-server::legal_docs_signer: ''
            urn:acronis.com::accounts::email_token_requester: ''
            urn:acronis.com::accounts::licensing_admin: ''
            urn:acronis.com::accounts::usage_reporter: ''
            urn:acronis.com::backup::backup_user: ''
            urn:acronis.com::backup::protection_admin: ''
            urn:acronis.com::files_cloud::sync_share_user: ''
            urn:acronis.com::acep::consumer: ''
            urn:acronis.com::account-server::security_groups_admin: ''
            urn:acronis.com::account-server::security_groups_viewer: ''
            urn:acronis.com::account-server::token_introspector: ''
            urn:acronis.com::account-server::custom_role_manager: ''
            urn:acronis.com::account-server::custom_role_viewer: ''
          tokenUrl: /api/2/idp/token
x-roles:
- name: public
  id: '1'
  description: public role
  x-tags:
  - public
- name: private
  id: '2'
  description: private role
  x-tags:
  - private
