openapi: 3.2.0
info:
  title: Vault Manager Storage Dirs API
  version: v1
servers:
- url: https://dev-cloud.acronis.com/api/vault_manager/v1
  variables: {}
tags:
- name: Storage Dirs
paths:
  /storage_dirs/{storageID}:
    get:
      operationId: FetchStorageFolders
      description: 'Available in on-premises version only.


        Fetches a list of top level storage folders.


        Detached folders are always listed.

        Attached folders listed depending on the `includeAttached` parameter value.'
      x-ExtJS: VaultManager.ListStorageTopDirs
      parameters:
      - name: includeAttached
        description: List all folders including attached to vaults.
        required: false
        in: query
        schema:
          description: List all folders including attached to vaults.
          default: false
          type: boolean
      - name: storageID
        required: true
        in: path
        schema:
          $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Storage dir
                  description: Storage dir description.
                  type: object
                  additionalProperties: false
                  required:
                  - name
                  - path
                  properties:
                    name:
                      type: string
                    path:
                      type: string
      security:
      - oauth2:
        - vault_manager::system_admin
        - vault_manager::admin
        - vault_manager::read
        - protection::readonly
      tags:
      - Storage Dirs
      summary: Fetch storage folders
      x-summary-source: derived
      x-operation-id-source: normalized
      x-operation-id-original: Fetch storage folders
  /storage_dirs/{storageID}/{path}:
    get:
      operationId: FetchStorageFoldersInPath
      description: 'Available in on-premises version only.


        Fetches a list of storage folders in path. Detached folders are always listed.


        Attached folders listed depending on the `includeAttached` parameter value.'
      x-ExtJS: VaultManager.ListStorageDirs
      parameters:
      - name: includeAttached
        description: List all folders including the ones attached to vaults.
        required: false
        in: query
        schema:
          description: List all folders including the ones attached to vaults.
          default: false
          type: boolean
      - name: storageID
        required: true
        in: path
        schema:
          $ref: '#/components/schemas/uuid'
      - name: path
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Storage dir
                  description: Storage dir description.
                  type: object
                  additionalProperties: false
                  required:
                  - name
                  - path
                  properties:
                    name:
                      type: string
                    path:
                      type: string
      security:
      - oauth2:
        - vault_manager::system_admin
        - vault_manager::admin
        - vault_manager::read
        - protection::readonly
      tags:
      - Storage Dirs
      summary: Fetch storage folders in path
      x-summary-source: derived
      x-operation-id-source: normalized
      x-operation-id-original: Fetch storage folders in path
components:
  schemas:
    uuid:
      description: Universally unique identifier.
      type: string
      format: uuid
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          scopes:
            vault_manager::system_admin: ''
            vault_manager::admin: ''
            vault_manager::core_restore: ''
            vault_manager::c2c_restore: ''
            vault_manager::orphanage_readwrite: ''
            vault_manager::read: ''
            protection::readonly: ''
            root_admin: ''
            partner_admin: ''
            infra_admin: ''
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
        authorizationCode:
          scopes:
            vault_manager::system_admin: ''
            vault_manager::admin: ''
            vault_manager::core_restore: ''
            vault_manager::c2c_restore: ''
            vault_manager::orphanage_readwrite: ''
            vault_manager::read: ''
            protection::readonly: ''
            root_admin: ''
            partner_admin: ''
            infra_admin: ''
          authorizationUrl: https://dev-cloud.acronis.com/api/2/idp/authorize
          tokenUrl: https://dev-cloud.acronis.com/api/2/idp/token
x-roles:
- name: public
  id: '1'
  description: public role
  x-tags:
  - public
- name: private
  id: '2'
  description: private role
  x-tags:
  - private
